version: '3.3'

services:
  lumen:
    # image: "php:8.0.0-apache"
    build: .
    container_name: "lumen"
    working_dir: "/var/www/html"
    volumes:
      - ./lumen:/var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    
  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  
  vue:
    image: "node:lts"
    container_name: "vue"
    user: "node"
    working_dir: "/usr/src/app"
    environment:
      - NODE_ENV=development
    volumes:
      - ./vue:/usr/src/app
    ports:
      - "80:80"
    command: "npm run dev -- --port 80"    

  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=schedule_email
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always